FROM python:3.10

WORKDIR /workspace

COPY ./requirements.txt .

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./vit/vit_server.py ./vit/cifar_model_script.pt ./vit/cifar10_classes.txt /workspace/

CMD ["gunicorn", "vit_server:app", "--workers", "2", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8080"]